### ISSUE TITLE
Check out this open source Heroku clone

### ISSUE THREAD

**Issue by aberba** [MartinNowak/heroku-buildpack-d#1]
http://dokku.viewdocs.io/dokku/

**Comment by aberba** [comment]
In your opinion, what will be the best way to host a large scale vibe.d app? 
(platform, Paas or ?, distributed session, storage, workers, replication, load balancing, scaling) Using MySQL storage

**Comment by MartinNowak** [comment]
@aberba [Distroless](https://github.com/GoogleCloudPlatform/distroless/tree/d061f8989a5fc1c59f2e84bfedb299a5fbb20cb6/base) comes to mind.

Any epoll linux would do just fine. Personally I prefer a user account and systemd, but docker is fine as well.
The community is performance oriented and less web-savy, so anything that resembles bare-metal (syscall) APIs is better suited than PaaS with custom (HTTP) APIs.
